// export const songs = [...Array(5).keys()].map((n) => ({
//   title: 'Song Number ' + Number(n + 1),
//   src: `https://www.soundhelix.com/examples/mp3/SoundHelix-Song-${Number(
//     n + 1
//   )}.mp3`,
// }));

export const songs = [
  {
    id: '1',
    country: 'KE',
    stationName: 'classic105',
    stationSignal: '105.2 FM',
    title: 'Classic 105',
    stationUrl: 'https://classic105.com/',
    mediaType: 'MP3',
    mime: 'audio/mpeg',
    src: 'https://atunwadigital.streamguys1.com/classic105',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-01 15:36:24',
  },
  {
    id: '2',
    country: 'KE',
    stationName: 'capitalfm',
    stationSignal: '98.4 FM',
    title: 'Capital FM (Nairobi)',
    stationUrl: 'https://www.capitalfm.co.ke',
    mediaType: 'MP3',
    mime: 'audio/mpeg',
    src: 'https://atunwadigital.streamguys1.com/capitalfm',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-01 13:29:15',
  },
  {
    id: '3',
    country: 'KE',
    stationName: 'inooro',
    stationSignal: '88.9 FM',
    title: 'Inooro FM (Nairobi',
    stationUrl: 'https://citizen.digital/radio/inooro-fm-live-5',
    mediaType: 'MP3',
    mime: 'audio/mpeg',
    src: 'https://inoorofm-atunwadigital.streamguys1.com/inoorofm',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-04 06:22:00',
  },
  {
    id: '4',
    country: 'KE',
    stationName: 'hbr',
    stationSignal: '103.5 FM',
    title: 'HBR (Nairobi',
    stationUrl: 'https://www.hbr.co.ke/',
    mediaType: 'MP3',
    mime: 'audio/mpeg',
    src: 'https://atunwadigital.streamguys1.com/homeboyzradio',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-01 13:29:15',
  },
  {
    id: '5',
    country: 'KE',
    stationName: 'citizen',
    stationSignal: '106.7 FM',
    title: 'Radio Citizen (Nairobi)',
    stationUrl: 'https://citizen.digital/radio/radio-citizen-13',
    mediaType: 'AAC',
    mime: 'audio/aac',
    src: 'https://radiocitizen-atunwadigital.streamguys1.com/radiocitizen',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-01 13:29:15',
  },
  {
    id: '6',
    country: 'KE',
    stationName: 'ghetto',
    stationSignal: '89.5 FM',
    title: 'Ghetto Radio (Nairobi)',
    stationUrl: 'https://www.hbr.co.ke/',
    mediaType: 'MP3',
    mime: 'audio/mpeg',
    src: 'https://stream.zeno.fm/eghcv7h647zuv.aac',
    is_default: '1',
    status: '1',
    last_update: '2023-11-01 13:27:23',
    tstamp: '2023-11-01 13:29:15',
  },
];
